vim.opt.guicursor = ""
vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.encoding = "utf-8"
vim.opt.hidden = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.autoindent = true
vim.opt.backup = false
vim.opt.writebackup = false
vim.opt.title = true
vim.opt.cursorline = true
vim.opt.cmdheight = 1
vim.opt.updatetime = 500
vim.g.mapleader = " "
